# -*- coding: utf-8 -*-
"""data_vis1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aef5_jh8nJJuQMihIF3J2CmhxZJiPTh7
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('data_vis1.csv')

df

plt.title('Marks')
plt.pie(df['marks'],labels=df['st_name'],autopct='%1.1f%%')
plt.show()
print("----------------------------------------------------------")
plt.title('Age')
plt.pie(df['age'],labels=df['st_name'],autopct='%1.1f%%')
plt.show()
print("----------------------------------------------------------")
plt.title('Study Hours')
plt.pie(df['st_hours'],labels=df['st_name'],autopct='%1.1f%%')
plt.show()

